version: '3.7'

services:
    lb:
        container_name: nginx
        image: jengweb/nginx:1.12
        ports:
            - 80:8080
        depends_on:
            - node-app
        volumes:
            - ./dockers/web/lb/logs:/opt/bitnami/nginx/logs
            - ./dockers/web/lb/nginx:/bitnami/nginx
    node-app:
        container_name: node_app
        build:
            context: ./node-app
            dockerfile: Dockerfile
        volumes:
            - ./node-app:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/build
        # ports:
        #     - 3000:3000
        # command: "npm start"
        # environment: 
        #     NODE_ENV: production
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            # MYSQL_HOST
            # - PMA_HOST=${MYSQL_HOST}
            # MARIADB_HOST
            - PMA_HOST=${MARIADB_HOST}
        restart: always
        depends_on:
            - mysqldb
    mariadb:
        image: mariadb:${MARIADB_VERSION}
        container_name: ${MARIADB_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        volumes:
            - ./dockers/web/mariadb:/var/lib/mysql
    # mysqldb:
    #     image: mysql:${MYSQL_VERSION}
    #     container_name: ${MYSQL_HOST}
    #     restart: always
    #     env_file:
    #         - ".env"
    #     environment:
    #         - MYSQL_DATABASE=${MYSQL_DATABASE}
    #         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #         - MYSQL_USER=${MYSQL_USER}
    #         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #     volumes:
    #         - ./dockers/web/mysql:/var/lib/mysql